version: '2'
services:
  web:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./logs/php:/var/log/php
      - ./logs/nginx:/var/log/nginx
      - ./logs/website:/var/www/html/storage/logs
      - ./images:/var/www/html/images
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=topditop
      - MYSQL_DATABASE=topditop
      - MYSQL_USER=topditop
      - MYSQL_PASSWORD=topditop
volumes:
  mysql: