version: '2'
services:
  web:
    build: .
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=topditop
      - MYSQL_DATABASE=topditop
      - MYSQL_USER=topditop
      - MYSQL_PASSWORD=topditop
volumes:
  mysql: